ase-aseglobal/Models/press_room.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class press_room
    {
        public long id { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
        public string title { get; set; }
        public string brief { get; set; }
        public string contents { get; set; }
        public Nullable<byte> sign { get; set; }
        public byte launch { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<long> sign_id { get; set; }
        public string lang { get; set; }
        public string urlid { get; set; }
        public string urlid2 { get; set; }
        public string og_image { get; set; }
    }
}

ase-aseglobal/Areas/backend/Controllers/PressRoomController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using web.Areas.backend.Models;
using web.Common;
using web.Models;

namespace web.Areas.backend.Controllers
{
    public class PressRoomController : BackendController
    {
        private Press_room_model model;
        protected List<Dictionary<string, int>> ratio = new List<Dictionary<string, int>>();

        public PressRoomController()
        {
            model = new Press_room_model();
        }
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List(int sort = 1, DateTime? searchP = null, string keyword = "")
        {
            Init();
            ViewBag.content_header_sub_title = "List";
            ViewBag.current_tab = "PressRoom";
            List<press_room> list = model.GetList(sort, searchP, keyword);
            ViewBag.sort = sort;
            ViewBag.keyword = keyword;
            ViewBag.searchP = searchP;
            return View(list);
        }

        public ActionResult Content(long param1 = 0)
        {
            Init();
            ViewBag.content_header_sub_title = "Content";
            ViewBag.current_tab = "PressRoom";
            press_room data;
            if (param1 == 0)
            {
                data = new press_room();
                data.publish_date = DateTime.Now;
                data.launch = 1;
                data.sign = 1;
            }
            else
            {
                data = model.GetData(param1);
            }
            this.ratio.Add(this.GetRatioSize(1280, 1280));
            ViewBag.ratio = ratio;
            return View(data);
        }

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Content(FormCollection fc)
        {
            Init();

            press_room data = FcToData(fc);
            if (UpdateData(data))
            {
                ShowUpdateMessage();
                return RedirectToAction("List", new { id = node.wm_url_id });
            }
            else
            {
                ShowUpdateFail();
            }

            this.ratio.Add(this.GetRatioSize(1280, 1280));
            ViewBag.ratio = ratio;
            return View(data);
        }

        private press_room FcToData(FormCollection fc)
        {
            this.fc = fc;
            press_room data = new press_room();

            long id = Tool.TryToParseLong(fc["id"]);
            if (id > 0)
            {
                data = model.GetData(id);
                if (data == null || data.id == 0)
                {
                    data.create_date = DateTime.Now;
                }
            }
            else
            {
                data.create_date = DateTime.Now;
            }

            data.title = fc["title"].Trim();
            data.brief = fc["brief"].Trim();
            data.contents = fc["contents"];
            data.urlid = fc["urlid"].Trim();
            data.urlid2 = fc["urlid2"].Trim();

            HttpPostedFileBase file = getFile("og_image");
            if (file != null)
            {
                data.og_image = resizeImage(moveFile(file), 512, 512);
            } else
            {
                
            }
            
            // 發佈日期
            if (!string.IsNullOrEmpty(fc["publish_date"]))
            {
                data.publish_date = Convert.ToDateTime(fc["publish_date"].Trim());
            }
            else
            {
                data.publish_date = null;
            }
            data.sign = Tool.TryToParseByte(fc["sign"]);
            data.launch = Tool.TryToParseByte(fc["launch"]);
            data.lang = fc["lang"].Trim();
            data.update_date = DateTime.Now;

            return data;
        }

        private bool UpdateData(press_room data)
        {
            Init();
            int affected_row = 0;

            //驗證
            //---------------------------------------------------------------------
            //錯誤訊息
            Dictionary<string, string> error = new Dictionary<string, string>();

            bool is_valid = true;

            #region 驗證
            if (fc["title"] != null && string.IsNullOrEmpty(data.title))
            {
                is_valid = false;
                error.Add("title", "Necessary");
            }
            if (fc["brief"] != null && string.IsNullOrEmpty(data.brief))
            {
                is_valid = false;
                error.Add("brief", "Necessary");
            }
            if (fc["contents"] != null && string.IsNullOrEmpty(data.contents))
            {
                is_valid = false;
                error.Add("contents", "Necessary");
            }
            if (data.publish_date == null)
            {
                is_valid = false;
                error.Add("publish_date", "Necessary");
            }
            //驗證urlid重複
            press_room checkUrl = model.checkUrlID(data.urlid);
            if (checkUrl != null)
            {
                if (data.id != checkUrl.id)
                {
                    is_valid = false;
                    error.Add("urlid", "Url Data duplication");
                }
            }
            if (fc["urlid"] != null && string.IsNullOrEmpty(data.urlid))
            {
                is_valid = false;
                error.Add("urlid", "Necessary");
            }
            #endregion

            TempData["error"] = error;
            //---------------------------------------------------------------------
            if (is_valid)
            {
                affected_row += model.SaveData(data);

                if (affected_row > 0)
                {
                    return true;
                }
            }
            return false;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteData(long param1)
        {
            if (param1 > 0)
            {
                Init();

                Dictionary<string, object> result = model.DeleteData(param1, Server.MapPath("~/" + website_path));

                int affected_row = (int)result["affected_row"];
                if (affected_row > 0)
                {
                    ShowUpdateMessage();
                }
                else
                {
                    ShowUpdateFail();
                }
                SecurityLog("delete", web_admin.ae_empnm + "[" + web_admin.ae_id + "]", "press_room", param1);
            }
            return RedirectToAction("List");
        }

        //ajax update launch, return value = 1:enable, 0:disable
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AjaxUpdateLaunch(string param1)
        {
            Init();
            long id = Tool.TryToParseLong(Server.HtmlEncode(param1));
            if (id == 0)
            {
                return Json("");
            }
            else
            {
                return Json(model.ToggleLaunch(id));
            }
        }

    }
}

ase-aseglobal/Controllers/PressRoomController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using web.Models;

namespace web.Controllers
{
    public class PressRoomController : FrontendController
    {
        private f_press_room_model model = new f_press_room_model();
        private F_sign_model sign_model = new F_sign_model();
        public ActionResult List(int year = 0, string title = "")
        {
            Init();

            if (browser_not_support)
            {
                return View(template + "/browser");
            }
            List<press_room> list = model.GetList(this.language.lang, false, year, title);

            //record parameters
            ViewBag.year = year;
            ViewBag.title = title;

            //year of data
            List<int> year_list = model.GetNewsYear(this.language.lang);
            ViewBag.year_list = year_list;

            return View(template + "/PressRoom/List", list);
        }
        //public ActionResult Content(long param1)
        public ActionResult Content(string param1)
        {
            Init();

            if (browser_not_support)
            {
                return View(template + "/browser");
            }

            press_room data = model.GetData(param1);

            List<press_room> list = model.GetList(this.language.lang);
            press_room prev = null, next = null;
            bool find = false;

            if (list.Count > 0)
            {
                foreach (press_room item in list)
                {
                    if (find)
                    {
                        next = item;
                        break;
                    }

                    if (item.id == data.id)
                    {
                        find = true;
                    }
                    else
                    {
                        prev = item;
                    }
                }
            }
            ViewBag.prev = prev;
            ViewBag.next = next;

            sign sign_data = sign_model.GetData();
            ViewBag.sign_data = sign_data;

            return View(template + "/PressRoom/Content", data);
        }
    }
}

ase-aseglobal/Controllers/Press_RoomController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using web.Common;
using web.Models;

namespace web.Controllers
{
    public class Press_RoomController : FrontendController
    {
        private f_press_room_model model = new f_press_room_model();
        private F_sign_model sign_model = new F_sign_model();
        public ActionResult Index(int year = 0, string title = "")
        {
            Init();

            if (browser_not_support)
            {
                return View(template + "/browser");
            }
            List<press_room> list;
            if (year == 0)
            {
                year = DateTime.Now.Year;
                list = model.GetList(this.language.lang, false, year, title);
                list.AddRange(model.GetList(this.language.lang, false, year - 1, title));
            } else
            {
                list = model.GetList(this.language.lang, false, year, title);
            }
            

            //record parameters
            ViewBag.year = year;
            ViewBag.query = title;

            //year of data
            List<int> year_list = model.GetNewsYear(this.language.lang);
            ViewBag.year_list = year_list;
            foreach (press_room item in list)
            {
                item.urlid = HttpUtility.UrlEncode(item.urlid.Replace(" ", "-"));
            }
            
            return View(template + "/PressRoom/List", list);
        }
        public new ActionResult Content(string param1 = "")
        {
            Init(); 
            press_room data = model.GetData(param1);
            List<press_room> list = model.GetList(this.language.lang);
            press_room prev = null, next = null;
            bool find = false;

            if (list.Count > 0)
            {
                foreach (press_room item in list)
                {
                    item.urlid = HttpUtility.UrlEncode(item.urlid.Replace(" ", "-"));
                    if (find)
                    {
                        next = item;
                        break;
                    }

                    if (item.id == data.id)
                    {
                        find = true;
                    }
                    else
                    {
                        prev = item;
                    }
                }
            }
            ViewBag.prev = prev;
            ViewBag.next = next;

            sign sign_data = sign_model.GetData();
            ViewBag.sign_data = sign_data;
            ViewBag.Title = data.title;
            ViewBag.webSiteDesc = data.brief;

            if ( data.urlid2 != null && data.urlid2 != "" )
            {
                if (language.lang == "en")
                {
                    ViewBag.zhURL = "/ch/press_room/content/"+ data.urlid2;
                }
                else
                {
                    ViewBag.enURL = "/en/press_room/content/"+ data.urlid2;
                }
            } else
            {
                if (language.lang == "en")
                {
                    ViewBag.zhURL = "/ch/press_room";
                }
                else
                {
                    ViewBag.enURL = "/en/press_room";
                }
            }

            if ( data.og_image != null && data.og_image != "" )
            {
                ViewBag.webSiteOgImage = "~" + data.og_image;
            }
            

            
            
            

            return View(template + "/PressRoom/Content", data);
        }
        public ActionResult Latest()
        {
            Init();
            if (browser_not_support)
            {
                return View(template + "/browser");
            }

            return View(template + "/PressRoom/Latest");
        }
    }
}

ase-aseglobal/Views/Shared/ch/PressRoom/Content.cshtml
@using web.Models;
@using System.Globalization;
@model press_room
@{
    Layout = "~/Views/Shared/ch/_Layout_seo.cshtml";

    press_room prev = ViewBag.prev;
    press_room next = ViewBag.next;
    sign sign_data = ViewBag.sign_data;
}

<!-- page Banner -->
<section id="page-vision" class="page-banner-s banner-press_room">

    <h1 class="page-title title-large ">新聞</h1>
</section>

<!--breadcrumbs-->
<div class="content-lg row">
    <div class="col-xs-12">
        <ol id="breadcrumbs" class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList">
            <!-- Project-B Fix, Apply New Breadcrumb -->
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/ch"><i class="icon-home"></i><span itemprop="name">Home</span></a>
                <meta itemprop="position" content="0" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/ch/about"><span itemprop="name">關於日月光</span></a>
                <meta itemprop="position" content="1" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item"><span itemprop="name">新聞中心</span></a>
                <meta itemprop="position" content="2" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/ch/press_room"><span itemprop="name">新聞</span></a>
                <meta itemprop="position" content="3" />
            </li>

            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item"><span itemprop="name">@Model.title</span></a>
                <meta itemprop="position" content="3" />
            </li>
        </ol>
    </div>
</div>
	<!-- Project-B Fix, Remove Old Breadcrumb -->
<!-- Press room Content -->
<section class="page-list-content">
    <div class="content-lg row">
        <div class="col-xs-12 list-base article-wrapper">
            <article class="article-detail">
                @{
                    string culture = ViewBag.language.lang == "ch" ? "zh-ch" : "en-US";
                    DateTime date = new DateTime(Model.publish_date.Value.Year, Model.publish_date.Value.Month, Model.publish_date.Value.Day);
                }
                <div class="date">
                    @if (culture == "en-US")
                    {
                        @date.ToString("MMM dd, yyyy", CultureInfo.CreateSpecificCulture(culture))
                    }
                    else
                    {
                        @date.ToString("yyyy/MM/dd", CultureInfo.CreateSpecificCulture(culture))
                    }
                </div>
                <div class="text-box">
                    <h2 class="title">@Model.title</h2>
                    @Html.Raw(Model.contents)
                    @if (Model.sign == 1)
                    {
                        @Html.Raw(sign_data.contents)
                    }

                    <div class="twitter-share-button" style="display:inline-block">
                        <a onclick="window.open('https://twitter.com/intent/tweet?url=@(Request.Url.AbsoluteUri.Replace("localhost:52845", "www.aseglobal.com"))&openExternalBrowser=1')">
                            <img id="imgTWT" src="~/public/frontend/images_ch/icon/twt-17.png" class="blog_content_icon_img" />
                        </a>
                    </div>
                    <div style="display:inline-block">
                        <a target="_blank" href="https://www.linkedin.com/sharing/share-offsite/?url=@(Request.Url.AbsoluteUri.Replace("localhost:52845", "www.aseglobal.com"))&openExternalBrowser=1">
                            <img src="~/public/frontend/images_ch/icon/in-19.png" class="blog_content_icon_img" border="0" />
                        </a>
                    </div>
                </div>
            </article>
        </div>

        <!-- Prev+Next -->
        <div class="col-xs-12 article-arrow">
            @if (prev != null && prev.id > 0)
            {
                <a href="@HttpUtility.UrlDecode(Url.Action("Content", "Press_Room", new { lang = ViewBag.language.lang, param1 = HttpUtility.UrlDecode(prev.urlid)}))" class="prev">
                    <div class="circle_button-wrapper">
                        <div class="circle_button darkgray"><i class="icon-arrow-left"></i></div>
                    </div>
                    <div class="text-wrapper">
                        <span class="tip">PREV NEWS</span>
                        <p class="text-box">@prev.title</p>
                    </div>
                </a>
            }
            @if (next != null && next.id > 0)
            {
                <a href="@HttpUtility.UrlDecode(Url.Action("Content", "Press_Room", new { lang = ViewBag.language.lang, param1 = HttpUtility.UrlDecode(next.urlid) }))" class="next">
                    <div class="text-wrapper">
                        <span class="tip">NEXT NEWS</span>
                        <p class="text-box">@next.title</p>
                    </div>
                    <div class="circle_button-wrapper">
                        <div class="circle_button darkgray"><i class="icon-arrow-right"></i></div>
                    </div>
                </a>
            }
        </div>
    </div>
</section>

<!-- Press Info -->
<section class="pressroom-info text-center">
    <h2 class="title" style="font-weight:600;">媒體聯絡</h2>
    <ul class="pressroom-info-list">
        <li class="item">
            <span class="country">美國/歐洲</span>
            <h4 class="name">Patricia MacLeod</h4>
            <p class="tel"><i class="icon-tel"></i>+1-408-6369500</p>
            <p class="mail"><i class="icon-mail"></i><a href="mailto:patricia.macleod@aseus.com">patricia.macleod@aseus.com</a></p>
        </li>
        <li class="item">
            <span class="country">亞洲</span>
            <h4 class="name">Jennifer Yuen</h4>
            <p class="tel"><i class="icon-tel"></i>+65-6631-4229</p>
            <p class="mail"><i class="icon-mail"></i><a href="mailto:jennifer.yuen@aseus.com">jennifer.yuen@aseus.com</a></p>
        </li>
    </ul>
</section>
<style>
    .pressroom-info-list .country {
        width: 90px;
        text-align: center;
    }
</style>

ase-aseglobal/Views/Shared/ch/PressRoom/List.cshtml
@using web.Models;
@using System.Globalization;
@model List<press_room>
@{
    Layout = "~/Views/Shared/ch/_Layout_seo.cshtml";
    List<int> year_list = ViewBag.year_list;
    ViewBag.Title = "新聞";
    ViewBag.zhURL = "/ch/pressroom/list";
}

<!-- page Banner -->
<section id="page-vision" class="page-banner-s banner-press_room">

    <h1 class="page-title title-large ">新聞</h1>
</section>

<!--breadcrumbs-->
<div class="content-lg row">
    <div class="col-xs-12">
        <ol id="breadcrumbs" class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList">
				<!-- Project-B Fix, Apply New Breadcrumb -->
				<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
					<a itemprop="item" href="/ch"><i class="icon-home"></i><span itemprop="name">Home</span></a>
					<meta itemprop="position" content="0" />
				</li>
				<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
					<a itemprop="item" href="/ch/about"><span itemprop="name">關於日月光</span></a>
					<meta itemprop="position" content="1" />
				</li>
				<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
					<a itemprop="item"><span itemprop="name">新聞中心</span></a>
					<meta itemprop="position" content="2" />
				</li>
				<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
					<a itemprop="item" href="/ch/press_room"><span itemprop="name">新聞</span></a>
					<meta itemprop="position" content="3" />
				</li>
        </ol>
    </div>
</div>
	<!-- Project-B Fix, Remove Old Breadcrumb -->
<!-- List Search -->
<section class="list-search">
    <div class="content-lg row">
        <form action="@Url.Action("Index", "Press_Room",new { lang = ViewBag.language.lang })" method="get">
            @Html.AntiForgeryToken()
            <div class="search-line search-group col-xs-6 col-md-3" style="float:left">
                <select name="year" id="" class="form-control" onchange="submit();">
                    <option value="0">所有新聞</option>
                    @if (year_list.Count > 0)
                    {
                        foreach (int year in year_list)
                        {
                            <option value="@year" @(ViewBag.year == year ? "selected" : "")>@year</option>
                        }
                    }
                </select>
                <span class="glyphicon glyphicon-triangle-bottom"></span>
            </div>
            <div class="search-line search-group col-xs-6 col-md-3" style="float:left">
                <input type="text" class="form-control" id="" placeholder="搜尋" name="title" value="@ViewBag.query">
                <button class="" type="submit"><i class="icon-search"></i></button>
            </div>
        </form>
    </div>
</section>

<!-- News list -->
<section class="page-list-content">
    <div class="content-lg row">
        @if (Model.Count > 0)
        {
            int prev_year = 0;
            string culture = ViewBag.language.lang == "ch" ? "zh-ch" : "en-US";
            <ul class="col-xs-12 list-base list-link list-timetip-line">
                @foreach (press_room item in Model)
                {
                    DateTime date = new DateTime(item.publish_date.Value.Year, item.publish_date.Value.Month, item.publish_date.Value.Day);

                    if (prev_year == 0 || prev_year != item.publish_date.Value.Year)
                    {
                        prev_year = item.publish_date.Value.Year;
                        <li class="time-tip">Posts from @prev_year</li>
                    }
                    <li>
                        @*item.id*@
                         <a href="@HttpUtility.UrlDecode(Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Press_Room", action = "Content", param1 =HttpUtility.UrlDecode(item.urlid)}))">                        
                             <div class="date">
                                @if (culture == "en-US")
                                {
                                    @date.ToString("MMM dd, yyyy", CultureInfo.CreateSpecificCulture(culture))
                                }
                                else
                                {
                                    @date.ToString("yyyy/MM/dd", CultureInfo.CreateSpecificCulture(culture))
                                }
                            </div>
                            <div class="text-box">
                                <h4 class="title">@item.title</h4>
                                <div class="circle_button-wrapper">
                                    <div class="circle_button darkgray"><i class="icon-arrow-right"></i></div>
                                </div>
                            </div>
                        </a>
                    </li>
                }
            </ul>
        }
    </div>
    <!-- Loader -->
    <!-- <div id="news-loader" class="loader text-center">
        <span>loading more news...</span>
        <ul> <li id='a'></li> <li id='b'></li> <li id='c'></li> <li id='d'></li> <li id='e'></li> <li id='f'></li> <li id='g'></li> <li id='h'></li> <li id='i'></li> </ul>
    </div> -->
</section>