ase-aseglobal/Areas/backend/Controllers/HtmlController.cs
using System.Web.Mvc;

namespace web.Areas.backend.Controllers
{
    public class HtmlController : BackendController
    {
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        
        public ActionResult List()
        {
            Init();
            return View();
        }

        public ActionResult Content()
        {
            Init();
            return View();
        }
    }
}

ase-aseglobal/Controllers/HtmlController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using web.Models;

namespace web.Controllers
{
    public class HtmlController : FrontendController
    {
        private F_ir_news_model ir_news_model = new F_ir_news_model();
        public ActionResult Index(string param1)
        {
            Init();
            if (browser_not_support)
            {
                return View(template + "/browser");
            }
            if (string.IsNullOrEmpty(param1))
            {
                AddJs("vendor/hammer.min.js");
                AddJs("index.js");
                return RedirectToAction("Index", "Home", new { lang = language.lang });
            }
            switch (param1)
            {
                case "ir":
                    List<ir_news> event_list = ir_news_model.GetList(this.language.lang, 1);
                    ViewBag.event_list = event_list;
                    List<ir_news> financial_list = ir_news_model.GetList(this.language.lang, 2);
                    ViewBag.financial_list = financial_list;
                    break;

                //case "award":
                //case "milestones":
                //case "ASE_Turnkey_Services":
                //case "community_engagement":
                    //AddJs("vendor/imagesloaded.pkgd.min.js");
                    //AddJs("vendor/masonry.pkgd.min.js");
                    //AddCss("vendor/ase_csr.css");
                    //break;
                    
                //case "sustainable_manufacturing":
                //    AddJs("vendor/jquery.jmap.min.js");
                //    AddJs("vendor/jquery.rwdImageMaps.js");
                //    break;

                case "products":
                //case "supplier_management":
                //case "solutions":
                    AddJs("ir.js");
                    break;
                    
                default:
                    break;
            }
            return View(template + "/Html/" + param1);
        }
        
    }
}

ase-aseglobal/Views/Shared/tw/Html/corporate_sustainability_management.cshtml
@using web.Models;
@using web.Common;
@{
    Layout = "~/Views/Shared/en/_Layout_seo.cshtml";
}

<!-- page Banner -->
<section id="page-vision" class="page-banner-s banner-csr">
    <h1 class="page-title-csr title-large">企業社會責任</h1>
</section>

<!--breadcrumbs-->
<div class="content-lg row">
    <div class="col-xs-12">
        <ol id="breadcrumbs" class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList">
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="@Url.Action("Index", "Home", new { lang = ViewBag.language.lang })"><i class="icon-home"></i><span itemprop="name">首頁</span></a>
                <meta itemprop="position" content="1" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "CSR" })"><span itemprop="name">企業社會責任</span></a>
                <meta itemprop="position" content="2" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="@Url.Action("Index", "Html", new { lang = ViewBag.language.lang, param1 = "corporate_sustainability_management" })"><span itemprop="name">Corporate Sustainability Management</span></a>
                <meta itemprop="position" content="3" />
            </li>
        </ol>
    </div>
</div>

<div class="breadcrumbs-pc pull-left" id="breadcrumbs-pc">
    <!-- PC版選單breadcrumbs內容 -->
    <ul class="breadcrumbs-view" id="breadcrumbs-view">
        <li class="dropdown-item">
            <span class="glyphicon glyphicon-menu-right"></span>
            <ul class="dropdown-list">
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Technology" })">技術</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Products" })">產品</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Solution" })">解決方案</a></li>
                <li><a href="@Url.Action("Index", "Html", new { lang = ViewBag.language.lang, param1 = "ir" })">投資人關係</a></li>
                <li><a class="active" href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "CSR" })">企業社會責任</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "About" })">了解日月光</a></li>
            </ul>
        </li>
        <li class="dropdown-item">
            <a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "CSR" })">CSR</a>
            <span class="glyphicon glyphicon-menu-right"></span>
            <ul class="dropdown-list">
                <li><a href="@Url.Action("Letter_Chairman", "CSR", new { lang = ViewBag.language.lang })">Letter from the Chairman</a></li>
                <li><a href="@Url.Action("Sustainability_Governance", "CSR", new { lang = ViewBag.language.lang })">Sustainability Governance</a></li>
                <li><a href="@Url.Action("Stakeholder_Engagement", "CSR", new { lang = ViewBag.language.lang })">Stakeholder Engagement</a></li>
                <li><a href="javascript:;">Corporate Governance</a></li>
                <li><a href="@Url.Action("environmental_sustainability", "CSR", new { lang = ViewBag.language.lang })">Environmental Sustainability</a></li>
                <li><a href="@Url.Action("Employee_Care_Development", "CSR", new { lang = ViewBag.language.lang })">Employee Care &amp; Development</a></li>
                <li><a href="@Url.Action("Index", "Html", new { lang = ViewBag.language.lang, param1 = "supply_chain_development" })">Supply Chain Development</a></li>
                <li><a href="@Url.Action("Corporate_Citizenship_Social_Involvement", "CSR", new { lang = ViewBag.language.lang })">Corporate Citizenship and Social Involvement</a></li>
                <li><a href="@Url.Action("Downloads", "CSR", new { lang = ViewBag.language.lang })">CSR Reports Downloads</a></li>
            </ul>
        </li>
    </ul>
</div>
	<!-- Letter from the Chairman -->
<section class="inside-article">
    <div class="content-lg row">
        <article class="col-xs-12">
            <h3 class="title">Corporate Sustainability Management </h3>
            <p>
                In the hope of fulfilling corporate social responsibility initiatives, promoting economic, environmental, and social advancement for purposes of sustainable development, and realizing our commitments, ASE has formally established Corporate Sustainability Management Organization in 2015, in which Corporate Sustainability Committee (the “CSC”) is appointed to oversee ASE’s sustainability issues directly. In 2015, we formulated and published ASE Group Corporate Sustainability and Citizenship Policy and ASE Corporate Social Responsibility Best Practice Principles; the former sets out the high level principles and commitments, and the latter introduces rules/procedures of dealing with material sustainability topics.
            </p>
            <h4 class="sub-title">Corporate Sustainability Management Organization</h4>
            <p>
                As the highest sustainable development governance body, the CSC is chaired by the Chief Operating Officer and comprised of ASE’s top management executives, who also serve on members of the board of directors. The CSC is responsible for overseeing corporate-wide sustainability affairs and reporting to the board of directors directly.<br><br>

                The CSC is fully supported by five sustainability taskforces, in which representatives from all of our corporate responsibility related business segments are brought together, and Vice Presidents and relevant department Directors are appointed as coordinators. The taskforces are designated in correspondence to material corporate responsibility and sustainability issues at ASE, including corporate governance, environmental sustainability, human capital, supply chain, corporate citizenship, and disclosure and stakeholder engagement.<br><br>

                Each taskforce is responsible for identifying sustainability issues, promoting action plans, and providing professional advice towards sustainability issues. The Corporate CSR Center serves as the secretariat of the CSC; its main responsibilities are to facilitate and integrate all initiatives related to groupwide sustainability affairs, and to improve the quality of ASE’s sustainability performances information disclosure. Our global manufacturing sites follow instructions and decisions of the CSC to integrate sustainability into their daily operation.
            </p>

            <h4 class="sub-title">Sustainability Management Framework</h4>
            <br>
            <div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
                <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/csr/corporate_sustainability_management1.png">
            </div>
            <div class="clearfix"></div>
            <br><br>
            <p>
                To realize ASE’s sustainability commitments under CSC’s sustainability management framework, business drivers or risks/opportunities related to corporate level sustainability issues are first identified and assessed. Responsive strategies are then determined following the ASE Group Sustainability Guidance, which stipulates policies and guidance for integrating sustainability into ASE’s operational management procedures. In consideration of the determined responsive strategies and the results of stakeholder engagement, focuses are defined, accompanied by key programs or items that aim to address targets set for each focus. Lastly, benefits or indicators are set to evaluate performances of the key items or programs, which contribute to decision-making process to enhance business operation.<br><br>

                In 2015, cross-regional and cross-functional teams within Finance, Legal, Internal Audit, Investor Relations, EHS and Facility, Human Resources, Procurement, Marketing Communication, Public Relations, and other related departments have become involved in CSC affairs, engaging with different stakeholders, and drawing and implementing sustainability tasks for each taskforce. Details of our performance against material sustainability issues are contained in the following chapters in this report.
            </p>


            <h4 class="sub-title">Corporate Sustainability Committee Organization Chart</h4>
            <br>
            <div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
                <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/csr/corporate_sustainability_management2.png">
            </div>
            <div class="clearfix"></div>
            <br><br>

        </article>
    </div>
</section>

ase-aseglobal/Views/Shared/tw/Html/green_lab.cshtml
@using web.Models;
@using web.Common;
@{
    Layout = "~/Views/Shared/en/_Layout_seo.cshtml";
}
<!-- page Banner -->
<section id="page-vision" class="page-banner-s banner-fit">
    <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/lab/banner_lab.jpg" />
    <h1 class="page-title">LAB</h1>
</section>

<!--breadcrumbs-->
<div class="content-lg row">
    <div class="col-xs-12">
        <ol id="breadcrumbs" class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList">
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="@Url.Action("Index", "Home", new { lang = ViewBag.language.lang })"><i class="icon-home"></i><span itemprop="name">首頁</span></a>
                <meta itemprop="position" content="1" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Lab" })"><span itemprop="name">LAB</span></a>
                <meta itemprop="position" content="2" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="#"><span itemprop="name">Package Design Services</span></a>
                <meta itemprop="position" content="3" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="@Url.Action("Index", "Html", new { lang = ViewBag.language.lang, param1 = "green_lab" })"><span itemprop="name">Electrical Lab</span></a>
                <meta itemprop="position" content="4" />
            </li>
        </ol>
    </div>
</div>

<div class="breadcrumbs-pc pull-left" id="breadcrumbs-pc">
    <!-- PC版選單breadcrumbs內容 -->
    <ul class="breadcrumbs-view" id="breadcrumbs-view">
        <li class="dropdown-item">
            <span class="glyphicon glyphicon-menu-right"></span>
            <ul class="dropdown-list">
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Technology" })">技術</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Products" })">產品</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Solution" })">解決方案</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Lab" })">投資人關係</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "CSR" })">企業社會責任</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "About" })">了解日月光</a></li>
            </ul>
        </li>
        <li class="dropdown-item">
            <a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Lab" })">LAB</a>
            <span class="glyphicon glyphicon-menu-right"></span>
            <ul class="dropdown-list">
                <li><a href="@Url.Action("Index", "Html", new { lang = ViewBag.language.lang, param1 = "electrical_lab" })">Electrical Lab</a></li>
                <li><a href="javascript:;">Material Lab</a></li>
                <li><a href="javascript:;">Stress-Thermal Lab</a></li>
                <li><a href="javascript:;">Chemical Lab</a></li>
                <li><a href="javascript:;">Analysis and Diagnosis Lab</a></li>
                <li><a href="javascript:;">Green Technology Lab</a></li>
                <li><a href="javascript:;">Mold Flow Lab</a></li>
                <li><a href="javascript:;">Compound Material Lab</a></li>
                <li><a href="javascript:;">Optical Lab</a></li>
                <li><a href="javascript:;">e-Thermal Simulator</a></li>
                <li><a href="javascript:;">e-Stress Simulator</a></li>
            </ul>
        </li>
    </ul>
</div>

<!-- Green Lab Content -->
<section>
    <div class="content-lg row">
        <div class="col-md-12">

            <div class="heading_3">Green Technology Lab</div><br>
            <p class="spacing2em">
                Green Technology Lab is an integrated laboratory for Green Product and Clean Process in connection to IC Packaging and Electronics Manufacturing. Our research focus on developing advanced Green Technology and creating a Sustainable and ECO-sufficient Environment.
            </p>
            <p>Role of Green Lab</p>
            <ul class="spacing1-5em">
                <li>Environmental risk assessment & resource integration</li>
                <li>Reusable material evaluation</li>
                <li>Green material development & Eco-Friendly Materials</li>
            </ul>
            <br><br>



            <div class="labs-container">
                <div class="left-lab-box">
                    <div class="circle_button darkgray"><i class="icon-arrow-left"></i></div>
                    &nbsp;&nbsp; Package Design Service
                </div>
                <div class="right-lab-box">
                    <!-- bottom pictures -->
                    <div class="bottom-pic-section">
                        <div class="heading_6 padding-left-10 padding-top-10">To see our Lab category<br><br></div>
                        <div class="bottom-pic-box">
                            <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/technology/u3119.png">
                            <div class="bottom-pic-text">Electrical Lab</div>
                        </div>
                        <div class="bottom-pic-box">
                            <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/technology/u3119.png">
                            <div class="bottom-pic-text">Material Lab</div>
                        </div>
                        <div class="bottom-pic-box">
                            <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/technology/u3119.png">
                            <div class="bottom-pic-text">Stress-Thermal Lab</div>
                        </div>
                        <div class="bottom-pic-box">
                            <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/technology/u3119.png">
                            <div class="bottom-pic-text">Chemical Lab</div>
                        </div>
                        <div class="bottom-pic-box">
                            <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/technology/u3119.png">
                            <div class="bottom-pic-text">Analysis and Diagnosis Lab</div>
                        </div>
                        <div class="bottom-pic-box">
                            <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/technology/u3119.png">
                            <div class="bottom-pic-text"><span class="grey-text">Green Technology Lab</span></div>
                        </div>
                        <div class="bottom-pic-box">
                            <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/technology/u3119.png">
                            <div class="bottom-pic-text">Mold Flow Lab</div>
                        </div>
                        <div class="bottom-pic-box">
                            <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/technology/u3119.png">
                            <div class="bottom-pic-text">Compound Material Lab</div>
                        </div>
                        <div class="bottom-pic-box">
                            <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/technology/u3119.png">
                            <div class="bottom-pic-text">Optical Lab</div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

ase-aseglobal/Views/Shared/tw/Html/grow_with_supply_chain.cshtml
@using web.Models;
@using web.Common;
@{
    Layout = "~/Views/Shared/tw/_Layout.cshtml";
}
<!-- page Banner -->
<section id="page-vision" class="page-banner-s banner-fit long-text">
    <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/supplier/banner_supplier.jpg" />
    <h1 class="page-title">供應商專區</h1>
</section>

<!--breadcrumbs-->
<div class="content-lg row">
    <div class="col-xs-12">
        <ol id="breadcrumbs" class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList">
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="@Url.Action("Index", "Home", new { lang = ViewBag.language.lang })"><i class="icon-home"></i><span itemprop="name">首頁</span></a>
                <meta itemprop="position" content="1" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Supplier" })"><span itemprop="name">供應商專區</span></a>
                <meta itemprop="position" content="2" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="@Url.Action("Index", "Html", new { lang = ViewBag.language.lang, param1 = "grow_with_supply_chain" })"><span itemprop="name">供應鏈永續倡議</span></a>
                <meta itemprop="position" content="3" />
            </li>
        </ol>
    </div>
</div>

<div class="breadcrumbs-pc pull-left" id="breadcrumbs-pc">
    <!-- PC版選單breadcrumbs內容 -->
    <ul class="breadcrumbs-view" id="breadcrumbs-view">
        <li class="dropdown-item">
            <span class="glyphicon glyphicon-menu-right"></span>
            <ul class="dropdown-list">
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Technology" })">技術</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Products" })">產品</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Solution" })">解決方案</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Lab" })">投資人關係</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "CSR" })">企業社會責任</a></li>
                <li><a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "About" })">了解日月光</a></li>
            </ul>
        </li>
        <li class="dropdown-item">
            <a href="@Url.RouteUrl(new { lang = ViewBag.language.lang, controller = "Supplier" })">供應商專區</a>
            <span class="glyphicon glyphicon-menu-right"></span>
            <ul class="dropdown-list">
                <li><a href="@Url.Action("Index", "Html", new { lang = ViewBag.language.lang, param1 = "message_from_top_management" })">總經理的話</a></li>
                <li><a href="@Url.Action("Index", "Html", new { lang = ViewBag.language.lang, param1 = "Supply_Chain_Development_Policy" })">供應鏈政策與行為準則</a></li>
                <li><a href="@Url.Action("Index", "Html", new { lang = ViewBag.language.lang, param1 = "supply_chain_development" })">供應鏈管理</a></li>
                <li><a href="@Url.Action("Index", "Html", new { lang = ViewBag.language.lang, param1 = "supply_chain_development_and_sustainability_management" })">Supply Chain Sustainable Management</a></li>
                <li><a href="@Url.Action("Index", "Supplier", new { lang = ViewBag.language.lang })">Become ASE Supply Chain Partner</a></li>
                <li><a href="@Url.Action("Index", "Html", new { lang = ViewBag.language.lang, param1 = "grow_with_supply_chain" })">供應鏈永續倡議</a></li>
            </ul>
        </li>
    </ul>
</div>

<section class="inside-article">
    <div class="content-lg row">
        <div class="col-xs-12">
            <h3 class="title">供應鏈永續倡議</h3>
            <p class="spacing2em">日月光致力於供應鏈管理與永續發展領域相關的對外倡議，並積極參與相關組織包含:</p>


            <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/supplier/grow_with_supply_chain1.gif" height="100" class="pull-right">
            <h4 class="sub-title">Responsible Business Alliance (RBA)</h4>
            <p class="spacing2em">2015年成為其會員，積極主動參與其年度會議，與其他會員共同於供應商管理議題上進行討論。</p>
            </br>

            <img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/supplier/grow_with_supply_chain2.png" height="120" class="pull-right margin-right-80">
            <h4 class="sub-title">Responsible Minerals Initiative (RMI)</h4>
            <p class="spacing2em">2015年成為其會員，並參與CMRT和盡責調查(Due Diligence, DD)工作團隊。</p>

        </div>
    </div>
</section>