ase-aseglobal/Models/contact.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public long id { get; set; }
        public Nullable<int> type { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string company { get; set; }
        public string contents { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string country { get; set; }
        public string receive_epaper { get; set; }
        public string ip { get; set; }
        public string lang { get; set; }
        public string country_code { get; set; }
        public string ext { get; set; }
    }
}

ase-aseglobal/Areas/backend/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using web.Areas.backend.Models;
using web.Common;
using web.Models;

namespace web.Areas.backend.Controllers
{
    public class ContactController : BackendController
    {
        private Contact_model model;
        protected List<Dictionary<string, int>> ratio = new List<Dictionary<string, int>>();

        public ContactController()
        {
            model = new Contact_model();
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        //useless
        public ActionResult List(int type = 0, string keyword = "", int sort = 0)
        {
            Init();

            ViewBag.content_header_sub_title = "List";
            ViewBag.current_tab = "Contact";

            List<contact> list = model.GetList(type, keyword, sort);
            //ViewBag.type = type;

            return View(list);
        }

        public ActionResult Content(long param1 = 0)
        {
            Init();
            ViewBag.content_header_sub_title = "Content";
            ViewBag.current_tab = "Contact";

            contact data;
            if (param1 == 0)
            {
                data = new contact();
                data.status = 0;
            }
            else
            {
                data = model.GetData(param1);
            }

            return View(data);
        }

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Content(FormCollection fc)
        {
            Init();

            contact data = FcToData(fc);
            if (UpdateData(data))
            {
                ShowUpdateMessage();
                return RedirectToAction("List");
            }
            else
            {
                ShowUpdateFail();
            }

            return View(data);
        }

        private contact FcToData(FormCollection fc)
        {
            this.fc = fc;
            contact data = new contact();
            long id = Tool.TryToParseLong(fc["id"]);
            if (id > 0)
            {
                data = model.GetData(id);
            }

            data.status = Tool.TryToParseInt(fc["status"]);
            data.update_date = DateTime.Now;
            return data;
        }

        private bool UpdateData(contact data)
        {
            Init();
            int affected_row = 0;

            //驗證
            //---------------------------------------------------------------------
            //錯誤訊息
            Dictionary<string, string> error = new Dictionary<string, string>();

            bool is_valid = true;

            #region 驗證
            #endregion

            TempData["error"] = error;
            //---------------------------------------------------------------------
            if (is_valid)
            {
                affected_row += model.SaveData(data);

                if (affected_row > 0)
                {
                    return true;
                }
                string security_cate = data.id == 0 ? "insert" : "update";
                SecurityLog(security_cate, web_admin.ae_empnm + "[" + web_admin.ae_id + "]", "contact", data.id);
            }
            return false;
        }



    }
}

ase-aseglobal/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using web.Common;
using web.Models;

namespace web.Controllers
{
    public class AboutController : FrontendController
    {
        private F_ir_news_model ir_news_model = new F_ir_news_model();
        private F_contact_model model = new F_contact_model();

        public ActionResult Index()
        {
            Init();
            if (browser_not_support)
            {
                return View(template + "/browser");
            }
            return View(template + "/About/about");
        }

        //public ActionResult website_feedback()
        //{
        //    Init();
        //    return View(template + "/About/website_feedback");
        //}
        public ActionResult milestones()
        {
            Init();
            if (browser_not_support)
            {
                return View(template + "/browser");
            }
            AddJs("vendor/imagesloaded.pkgd.min.js");
            AddJs("vendor/masonry.pkgd.min.js");
            AddCss("vendor/ase_csr.css");
            return View(template + "/About/milestones");
        }
        public ActionResult Awards()
        {
            Init();
            if (browser_not_support)
            {
                return View(template + "/browser");
            }
            AddJs("vendor/imagesloaded.pkgd.min.js");
            AddJs("vendor/masonry.pkgd.min.js");
            AddCss("vendor/ase_csr.css");
            return View(template + "/About/Awards");
        }
        public ActionResult ASE_Turnkey_Services()
        {
            Init();
            if (browser_not_support)
            {
                return View(template + "/browser");
            }
            AddJs("vendor/imagesloaded.pkgd.min.js");
            AddJs("vendor/masonry.pkgd.min.js");
            AddCss("vendor/ase_csr.css");
            return View(template + "/About/ASE_Turnkey_Services");
        }
        public ActionResult Manufacturing_Facilities()
        {
            Init();
            if (browser_not_support)
            {
                return View(template + "/browser");
            }
            return View(template + "/About/Manufacturing_Facilities");
        }
        public ActionResult Careers()
        {
            Init();
            if (browser_not_support)
            {
                return View(template + "/browser");
            }
            return View(template + "/About/Careers");
        }
        public ActionResult organization_chart()
        {
            Init();
            if (browser_not_support)
            {
                return View(template + "/browser");
            }
            return View(template + "/About/organization_chart");
        }

        public ActionResult plants_offices()
        {
            Init();
            if (browser_not_support)
            {
                return View(template + "/browser");
            }
            return View(template + "/About/plants_offices");
        }
        //public ActionResult plants_offices_ase()
        //{
        //    Init();
        //    if (browser_not_support)
        //    {
        //        return View(template + "/browser");
        //    }
        //    return View(template + "/About/plants_offices_ase");
        //}
        //public ActionResult plants_offices_ise()
        //{
        //    Init();
        //    if (browser_not_support)
        //    {
        //        return View(template + "/browser");
        //    }
        //    return View(template + "/About/plants_offices_ise");
        //}
        //public ActionResult plants_offices_usi()
        //{
        //    Init();
        //    if (browser_not_support)
        //    {
        //        return View(template + "/browser");
        //    }
        //    return View(template + "/About/plants_offices_usi");
        //}


        public ActionResult Contact(contact data)
        {
            Init();
            AddJs("vendor/hammer.min.js");
            AddJs("index.js");

            if (browser_not_support)
            {
                return View(template + "/browser");
            }
            ViewBag.country_list = _getCountry();

            var countries = ISO3166.GetCollection();
            List<string> country_code_list = new List<string>();
            foreach (var item in countries)
            {
                if (item.DialCodes != null && country_code_list.Where(x => x == item.DialCodes.FirstOrDefault()).Count() == 0)
                {
                    string temp_code = item.DialCodes.FirstOrDefault();
                    country_code_list.Add(temp_code);
                }
            }
            country_code_list.Sort();
            ViewBag.country_code = country_code_list;

            return View(template + "/About/Contact", data);
        }

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Form(FormCollection fc)
        {
            Init();

            bool isValid = true;
            Dictionary<string, string> error = new Dictionary<string, string>();
            string msg = "Necessary";
            string type = "", name = "", email = "", country_code = "", phone = "", ext = "", company = "", contents = "", user_ip = "";

            #region 驗證資料/儲存資料

            type = fc["type"].Trim();
            if (string.IsNullOrEmpty(type))
            {
                isValid = false;
                error.Add("type", msg);
            }
            name = fc["name"].Trim();
            if (string.IsNullOrEmpty(name))
            {
                isValid = false;
                error.Add("name", msg);
            }

            email = fc["email"].Trim();
            if (string.IsNullOrEmpty(email))
            {
                isValid = false;
                error.Add("email", msg);
            }
            else if (!Tool.IsEmail(email))
            {
                isValid = false;
                error.Add("email", "Must be a valid email address.");
            }

            country_code = fc["country_code"].Trim();
            phone = fc["phone"].Trim();
            ext = fc["ext"].Trim();
            company = fc["company"].Trim();

            contents = fc["contents"].Trim();
            if (string.IsNullOrEmpty(contents))
            {
                isValid = false;
                error.Add("contents", msg);
            }

            // 使用者IP位置
            string HTTP_VIA = Request.ServerVariables["HTTP_VIA"];
            if (string.IsNullOrEmpty(HTTP_VIA))
            {
                string REMOTE_ADDR = Request.ServerVariables["REMOTE_ADDR"];
                user_ip = REMOTE_ADDR;
            }
            else
            {
                string HTTP_X_FORWARDED_FOR = Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
                user_ip = HTTP_X_FORWARDED_FOR;
            }
            #endregion

            contact data = new contact();
            data.create_date = DateTime.Now;
            data.lang = language.lang;
            data.type = Tool.TryToParseInt(type);
            data.name = name;
            data.email = email;
            data.country_code = country_code;
            data.phone = phone;
            data.ext = ext;
            data.company = company;
            data.contents = contents;
            data.ip = user_ip;

            string type_title = "";
            switch (data.type)
            {
                case 1:
                    type_title = "Website Feedback";
                    break;

                case 2:
                    type_title = "Media Enquiries - PR Contacts_USA/Europe";
                    break;

                case 3:
                    type_title = "Media Enquiries - PR Contacts_Asia Pacific";
                    break;

                case 4:
                    type_title = "CSR Contacts";
                    break;

                default:
                    break;
            }
            if (isValid)
            {
                model.SaveData(data);
                string tmpString = "<tr><td style='font-family: \"微軟正黑體\", Arial; font-size: 14px; line-height: 1.7em; box-sizing: border-box; padding: 10px; color:#504e4f;border-bottom:1px solid #e6e6e6;width: 150px;vertical-align: top;'>#TITLE#：</td><td style='font-family: \"微軟正黑體\", Arial; font-size: 14px; line-height: 1.7em; box-sizing: border-box; padding:10px; color:#504e4f;border-bottom:1px solid #e6e6e6;'>#CONTENT#</td></p></tr>";
                string form_content = "";
                form_content += tmpString.Replace("#TITLE#", "Date").Replace("#CONTENT#", data.create_date.ToString());
                form_content += tmpString.Replace("#TITLE#", "Question Type").Replace("#CONTENT#", type_title);
                form_content += tmpString.Replace("#TITLE#", "Name").Replace("#CONTENT#", data.name);
                form_content += tmpString.Replace("#TITLE#", "Email").Replace("#CONTENT#", data.email);
                form_content += tmpString.Replace("#TITLE#", "Phone").Replace("#CONTENT#", data.country_code + data.phone + data.ext);
                form_content += tmpString.Replace("#TITLE#", "Company").Replace("#CONTENT#", data.company);
                form_content += tmpString.Replace("#TITLE#", "Content").Replace("#CONTENT#", data.contents);

                Uri uri = Request.Url;
                string host = uri.Scheme + Uri.SchemeDelimiter + uri.Host + ":" + uri.Port;
                string mail_content = Tool.GetFileToString(Server.MapPath("~/Common/contact_mail.html"));
                mail_content = mail_content.Replace("#picture#", host + @Url.Content("~/public/frontend/images/logo-en.png"));
                mail_content = mail_content.Replace("#mail_content#", form_content);

                //Mail Object settings
                // get (contact us) email receiver

ase-aseglobal/Views/Shared/ch/About/Contact.cshtml
@using web.Models;
@using web.Common;
@model contact
@{
    Layout = "~/Views/Shared/ch/_Layout_seo.cshtml";
    Dictionary<string, string> error = (Dictionary<string, string>)TempData["error"];
    List<string> country_list = ViewBag.country_list;
    ViewBag.Title = "聯絡我們";
}

<!-- page Banner -->
<section id="page-vision" class="page-banner-s banner-about">
    <h1 class="page-title title-large">關於日月光</h1>
    <video poster="https://2311cdn.r.worldssl.net/pic/public/frontend/images/about/video.jpg" class="about-video" id="bgvid" playsinline autoplay muted loop>
        <!-- 使用JS增加Source -->
    </video>
</section>

<!--麵包屑-->
<div class="content-lg row">
    <div class="col-xs-12">
        <ol id="breadcrumbs" class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList">
			<!-- Project-B Fix, Apply New Breadcrumb -->
			<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
				<a itemprop="item" href="/ch"><i class="icon-home"></i><span itemprop="name">Home</span></a>
				<meta itemprop="position" content="0" />
			</li>
			<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
				<a itemprop="item" href="/ch/about"><span itemprop="name">關於日月光</span></a>
				<meta itemprop="position" content="1" />
			</li>
			<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
				<a itemprop="item"><span itemprop="name">聯絡我們</span></a>
				<meta itemprop="position" content="2" />
			</li>
        </ol>
    </div>
</div>

	<!-- Project-B Fix, Remove Old Breadcrumb -->

<section class="inside-article">
    <div class="content-lg row">
        <article class="col-xs-12">
            <h3 class="title">聯絡我們</h3>
            <br>
            <h4 class="sub-title">業務聯絡</h4>
            <p>聯絡各地業務代表，詳細資訊請瀏覽<a href="@Url.Action("plants_offices", "About", new { lang = ViewBag.language.lang })">業務據點</a>。</p>
            <br>
            <h4 class="sub-title">媒體查詢</h4>
            <p style="padding-bottom: 5px;"><b>美國/歐洲</b><br />
                Patricia MacLeod<br />
                1-408-636-9500<br />
                <a href="mailto:patricia.macleod@aseus.com">patricia.macleod@aseus.com</a></p>
            <p><b>亞洲</b><br />
                Jennifer Yuen<br />
                65-6631-4229<br />
                <a href="mailto:jennifer.yuen@aseus.com">jennifer.yuen@aseus.com</a></p>
            <br>
            <h4 class="sub-title">企業社會責任詢問</h4>
            <p>若您對於日月光企業社會責任有任何建議與問題，請聯繫：<a href="mailto:ase_csr@aseglobal.com">ase_csr@aseglobal.com</a>。</p>
            <br>
            <h4 class="sub-title">網站詢問</h4>
            <p>若您有任何關於網站的問題、意見或建議，請直接<a href="mailto:ase_webmaster@aseglobal.com">聯繫我們</a>。</p>
            <br>
            <h4 class="sub-title">Logo與視覺規範指南</h4>
            <p>對於正確使用日月光與相關公司的Logo或其它受版權保護素材，如有任何問題或欲申請授權使用，請聯繫：<a href="mailto:corp_comms@aseglobal.com">corp_comms@aseglobal.com</a>。</p>
            <br>
        </article>
    </div>
</section>

ase-aseglobal/Views/Shared/ch/About/about_careers.cshtml
@using web.Models;
@using web.Common;
@{
    Layout = "~/Views/Shared/ch/_Layout_seo.cshtml";
}
	<!-- page Banner -->
	<section id="page-vision" class="page-banner-s banner-about">
		<h1 class="page-title title-large">了解日月光</h1>
		<video poster="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/about/video.jpg")" class="about-video" id="bgvid" playsinline autoplay muted loop>
			<!-- 使用JS增加Source -->
		</video>
	</section>

	<!--麵包屑-->
	<div class="content-lg row">
		<div class="col-xs-12">
			<ol id="breadcrumbs" class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList">
				<!-- Project-B Fix, Apply New Breadcrumb -->
				<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
					<a itemprop="item" href="/ch"><i class="icon-home"></i><span itemprop="name">Home</span></a>
					<meta itemprop="position" content="0" />
				</li>
			</ol>
		</div>
	</div>

	<!-- Project-B Fix, Remove Old Breadcrumb -->

	<!-- Content -->


	<!-- ================ start of content ================  -->
	<section class="inside-article">
		<div class="content-lg row">
			<div class="col-md-12">
				<h3 class="title">人才招募</h3>
			</div>

			<div class="col-md-6">
				<p><h4>日月光工作機會</h4></p>
				<p>日月光集團為全球最大半導體製造服務公司，自1984年起即提供包括晶片前段測試及晶圓針測至後段之封裝、材料及成品測試的一元化服務，以及集團中的環隆電子(USI)，提供完善的電子製造服務整體解決方案。我們專注於運用我們先進封裝、材料、及測試技術，在半導體製程每個階段皆提供附加價值給全球客戶。</br>
				身為全球電子供應鏈中不可或缺的環節，日月光在全球各地有製造據點，現有超過六萬八千名員工。日月光專注投入做為客戶的虛擬工廠，以務實勤奮的精神提供猷如客戶團隊延伸的服務。
				</p>
			</div>
			<div class="col-md-6 padding-bottom10">
				<img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/about/careers/careers1.jpg")">
			</div>			
			<div class="col-md-6 padding-bottom10">
				<img src="https://2311cdn.r.worldssl.net/pic/public/frontend/images_ch/about/careers/careers2.jpg")">
			</div>
			<div class="col-md-6">
				<p>日月光集團的全球營運據點包括臺灣、中國、南韓、日本、馬來西亞、新加坡等地。除此之外，我們在美國與歐洲設立業務辦公室，日月光將近70%集團營收來自於這兩個地區。日月光的全球策略性營運服務平均分佈於3C市場的客戶群，使日月光成為全球半導體產業的知名企業。</p>				
			</div>
			<div class="col-md-12 padding-top40 padding-bottom40">
				<p><h4>日月光集團全球營運據點工作機會：</h4>
					日月光高雄廠：<a href="http://www.asekh.aseglobal.com/content/5-51c.html">線上召募</a><br>
					日月光中壢廠：<a href="http://www.asecl.aseglobal.com/content/HumanResourceDevelopment_c.html">線上召募</a><br>
					日月光日本廠：<a href="mailto:uegaki@aseglobal.com">uegaki@aseglobal.com</a><br>
					日月光韓國廠：<a href="mailto:career@asekr.com">career@asekr.com</a><br>
					日月光馬來西亞廠：<a href="http://www3.asemal.com.my/Content/HR/jobs">線上召募</a><br>
					日月光新加坡廠：<a href="http://www.aseglobal.com.sg/index.php/career/job-application/">線上召募</a><br>
					日月光上海廠：<a href="http://www.asesh.aseglobal.com/content/5-5c.html">線上召募</a><br>
					日月光昆山廠：<a href="http://www.aseks.aseglobal.com/content/5-5c.html">線上召募</a><br>
					蘇州日月新：<a href="http://www.asen.aseglobal.com/content/CareerOpportunities.html">線上召募</a><br>
					日月光美國辦公室：<a href="mailto:hr@aseus.com">hr@aseus.com</a><br>
					日月光歐洲辦公室：<a href="mailto:juliette.handwerker@aseeu.com">juliette.handwerker@aseeu.com</a><br>
					ISE Labs: <a href="mailto:mwang@iselabs.com">mwang@iselabs.com</a><br>
					環隆電氣：<a href="http://www.usi.com.tw/Career_job.html">線上召募</a><br>
					國防役招募 (日月光高雄廠及中壢廠)：<a href="http://www.aseglobal.com/career/reserve_duty_officer/">線上召募</a><br>
				</p>
			</div>



		</div>
	</section>

ase-aseglobal/Views/Shared/ch/About/contact_us.cshtml
@using web.Models;
@using web.Common;
@model contact
@{
    Layout = "~/Views/Shared/ch/_Layout_seo.cshtml";
    Dictionary<string, string> error = (Dictionary<string, string>)TempData["error"];
    List<string> country_list = ViewBag.country_list;
}

<!-- page Banner -->
<section id="page-vision" class="page-banner-s banner-about">
    <h1 class="page-title title-large">了解日月光</h1>
    <video poster="https://2311cdn.r.worldssl.net/pic/public/frontend/images/about/video.jpg" class="about-video" id="bgvid" playsinline autoplay muted loop>
        <!-- 使用JS增加Source -->
    </video>
</section>

<!--麵包屑-->
<div class="content-lg row">
    <div class="col-xs-12">
        <ol id="breadcrumbs" class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList">
				<!-- Project-B Fix, Apply New Breadcrumb -->
				<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
					<a itemprop="item" href="/ch"><i class="icon-home"></i><span itemprop="name">Home</span></a>
					<meta itemprop="position" content="0" />
				</li>
        </ol>
    </div>
</div>

	<!-- Project-B Fix, Remove Old Breadcrumb -->

<section class="inside-article">
    <div class="content-lg row">
        <article class="col-xs-12">
            <h3 class="title">聯絡日月光</h3>
        </article>
    </div>
</section>
<section class="page-list-content section-contact">
   <!--<div class="content-lg row">
        <div class="col-xs-12">
            <h4>*必填欄位</h4>
        </div>
    </div>
    <div class="content-lg row">
        <div class="col-xs-12">
            <div>
            @using (Html.BeginForm("Form", "About", FormMethod.Post, new { enctype = "multipart/form-data", id = "form1" }))
            {
                @Html.AntiForgeryToken()
                <div class="list">
                    <div class="remind">若您有任何問題、意見或建議，請填寫以下資料。謝謝您!</div>
                    <div class="row row_padding_0">
                        <div class="col-xs-12 col-sm-12 col-md-6">
                            <div class="content-wrapper">
                                <div class="require">
                                    <label>問題類型 :</label>
                                    <select name="type">
                                        <option value="">Please Select</option>
                                        <option value="1" @(Model.type == 1 ? "selected" : "")>網站詢問</option>
                                        <option value="2" @(Model.type == 2 ? "selected" : "")>媒體聯絡 - 美國/歐洲媒體窗口</option>
                                        <option value="3" @(Model.type == 3 ? "selected" : "")>媒體聯絡 - 亞洲媒體窗口</option>
                                        <option value="4" @(Model.type == 4 ? "selected" : "")>企業社會責任詢問</option>
                                    </select>
                                    <span class="text-red">@ViewHelper.GetErrorMsg(error, "type")</span>
                                </div>
                                <div class="require"><label>姓名:</label><input name="name" type="text" required value="@(Model.name)"/></div>
                                <span class="text-red">@ViewHelper.GetErrorMsg(error, "name")</span>
                                <div class="require"><label>電子信箱:</label><input name="email" type="email" required value="@(Model.email)"/></div>
                                <span class="text-red">@ViewHelper.GetErrorMsg(error, "email")</span>

                                <div class="phone">
                                    <label>電話 :</label>
                                    <div>
                                        <span>+</span>
                                        <span>
                                            <select name="country_code">
                                                @foreach (string item in ViewBag.country_code)
                                                {
                                                    if (Tool.IsNumeric(item))
                                                    {
                                                        <option value="@(item)" @(Model.country_code == item ? "selected" : "")>@(item)</option>
                                                    }
                                                }
                                            </select>
                                        </span>
                                        <span><input name="phone" type="text"  value="@(Model.phone)"/></span>
                                        <span>(分機)</span>
                                        <span><input name="ext" type="text" value="@(Model.ext)" /></span>
                                    </div>
                                </div>
                                <div>
                                    <label>公司 / 組織:</label><input name="company" type="text" value="@(Model.company)" />
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6">
                            <div class="content-wrapper fixed">
                                <div class="require question">
                                    <label>問題，意見或建議:</label>
                                    <textarea name="contents" required>@(Model.contents)</textarea>
                                    <span class="text-red">@ViewHelper.GetErrorMsg(error, "contents")</span>
                                </div>
                                <div class="agree-div">
                                    <div>
                                        <input name="agree" type="checkbox" value="" id='agree01' required/><label for="agree01">I agree to the <a href="javascript:;">Terms of Use</a></label>
                                    </div>
                                    <button type="submit" id="submit_btn">提交問卷</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>-->
    <div class="content-lg row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="list">
                <div class="title">
                    網站詢問
                    <a href="#open01" data-toggle="collapse" class="collapsed feedback"></a>
                </div>
                <div class="content-wrapper content-feedback">
                    <div id="open01" class="collapse text-center">
                        若您有任何關於網站的問題、意見或建議，請<a href="mailto:ase_webmaster@aseglobal.com">直接聯繫</a> 我們。
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-lg row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="list">
                <div class="title">
                    業務聯絡
                    <a href="#open02" data-toggle="collapse" class="collapsed feedback"></a>
                </div>
                <div class="content-wrapper content-feedback">
                    <div id="open02" class="collapse text-center">
                        聯絡各地業務代表，詳細資訊請瀏覽<a href="@Url.Action("Index", "Html", new { lang = ViewBag.language.lang, param1 = "plants_offices_ase" })">業務據點</a>。
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-lg row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="list">
                <div class="title">
                    媒體查詢
                    <a href="#open03" data-toggle="collapse" class="collapsed feedback"></a>
                </div>
                <div class="content-wrapper content-feedback">
                    <div id="open03" class="collapse text-center">
                        <div class="media-enquiries">
                            
                            
                                <div class="col text-center">
                                    <b>美國/歐洲</b><br />
                                    Patricia MacLeod<br />
                                    1-408-636-9500<br />
                                    <a href="mailto:patricia.macleod@aseus.com">patricia.macleod@aseus.com</a>
                                </div>
                                <div class="col text-center">
                                    <b>亞洲</b><br />
                                    Jennifer Yuen<br />
                                    65-6631-4229<br />
                                    <a href="mailto:jennifer.yuen@aseus.com">jennifer.yuen@aseus.com</a>
                                </div>
                         
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
	    <div class="content-lg row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="list">
                <div class="title">
                    企業社會責任詢問
                    <a href="#open05" data-toggle="collapse" class="collapsed feedback"></a>
                </div>
                <div class="content-wrapper content-feedback">
                    <div id="open05" class="collapse text-center">
                        若您對於日月光企業社會責任有任何建議與問題，請聯繫：<a href="mailto:ase_csr@aseglobal.com">ase_csr@aseglobal.com</a>.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-lg row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="list">
                <div class="title">
                    投資人關係聯絡
                    <a href="#open04" data-toggle="collapse" class="collapsed feedback"></a>
                </div>
                <div class="content-wrapper content-feedback">
                    <div id="open04" class="collapse text-center">
                        若您有任何關於日月光投資人關係服務的資訊與建議，請瀏覽<a href="/public/ch/ir.html">投資人關係網頁</a>。
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<style>
    .text-red {
        color: red;
    }
    .text-center{
        text-align:center !important;
    }
</style>
<script>
    $(document).ready(function () {
        $('#submit_btn').on('click', function (e) {
            e.preventDefault();
            if (!$('#agree01').prop('checked')) {
                swal(
                    'OOPS ...',
                    'Sorry, please agree to ASE "Terms of Use" to complete form',
                    'warning'
                );
            } else {
                $('#form1').submit();
            }
        });
    });
</script>